### ISSUE TITLE
Project inclusion request: yasfw

### ISSUE THREAD

**Issue by DDoSolitary** [dokan-dev/dokan-dev.github.io#7]
Hello, I just created a new SSHFS for Windows project: [yasfw](https://github.com/DDoSolitary/yasfw)

Some advantages compared to existing implementations:

- Supports case-insensitive paths
- Written in Rust, so has better performance in theory compared to existing .NET-based projects
- Based on the widely used libssh library, so has better compatibility with current OpenSSH servers.

Could you please include this project in the `Projects. See it working.` section of Dokan's home page? Thanks!

**Comment by Liryna** [comment]
Hey @DDoSolitary ,

That's a great project you have hear! Especially in Rust :heart: 
Would you be interested to create/maintain a library that Rust dev could use for dokan ?
https://github.com/DDoSolitary/yasfw/blob/master/src/dokan.rs
No hurry as I have seen you just started you project but if you are interested to be part of https://github.com/dokan-dev :+1: 

Glad seeing you part of the community :trophy: https://github.com/dokan-dev/dokan-dev.github.io/commit/426abe2126c33ecffa542fc57ddc05cd54d8967a

**Comment by DDoSolitary** [comment]
> Would you be interested to create/maintain a library that Rust dev could use for dokan ?
https://github.com/DDoSolitary/yasfw/blob/master/src/dokan.rs
> No hurry as I have seen you just started you project but if you are interested to be part of https://github.com/dokan-dev 👍

Of course yes. Actually I've already considered creating a separate Rust binding library for Dokan when I started this project, but decided to keep things simple so that I could focus on the development of yasfw.

To turn the current bindings into a usable library, there're still some work left to be done:

- The current code only provides raw bindings to Dokan's C functions, so Rust users have to write some dirty unsafe code to use them. I plan to properly wrap these unsafe functions and create a Rust-friendly API.
- The struct definitions in my current dokan.rs are imconplete, and some struct pointers that I don't use in yasfw are replaced by `*mut c_void` (i.e. `void *`).
- I used the `winapi` crate for some of the struct & constant definitions. However, this crate uses Rust contants for C constants that are acutally enums or bit flags semantically. Probably it's better to wrap these constants using Rust enums or the `bitflags` crate.

I'll work on these things when I have free time, though they won't be completed very soon. Except the young yasfw project, I have several other projects that I have to maintain, and a lot of things to work on in school

**Comment by Liryna** [comment]
No problem @DDoSolitary , if the time comes, please ping me to join dokan-dev!

**Comment by DDoSolitary** [comment]
Some good news: Initial developmeng of Rust bindings is done and currently I'm working on unit tests.

**Comment by Liryna** [comment]
Good to hear! 😍 I will be able to help you setting up an appveyor for running the CI on those unit tests when the time will come.

**Comment by DDoSolitary** [comment]
@Liryna Unit tests are completed now. Documentation may take some more time (because I'm not very good at writing that XD). However, I think I should be able to get the source code published first after joining dokan-dev.

**Comment by Liryna** [comment]
@DDoSolitary I added the repository https://github.com/dokan-dev/dokan-rust and sent you an invitation to join the new Rust team! If you need anything please let me know
For the documentation, do not hesitate to reusing existing doc of dokan :)
